### ISSUE TITLE
How to test in Qemu

### ISSUE THREAD

**Issue by elliott10** [vgarleanu/rtl8139-rs#1]
How to test in Qemu ?
And How to build a driver testing env ?

**Comment by vgarleanu** [comment]
Hi, to test this you would need to find out the base port of the rtl8139 NIC by scanning and parsing the PCI table. You can then create the driver by calling `RTL8139::preload_uncheck` and then `load`. After this you should be able to send and receive Ether2 frames.
You can see an async example integration here: https://github.com/vgarleanu/vallicks/blob/master/src/net/mod.rs

**Comment by elliott10** [comment]
Thanks！
